.. _advanced_api:

Advanced API
============

.. _advanced_api_sending:

Sending Email
-------------

.. autoclass:: pystmark.PystSender
    :inherited-members:

.. autoclass:: pystmark.PystBatchSender
    :inherited-members:

.. _advanced_api_bounce_handling:

Bounce Handling
---------------

.. autoclass:: pystmark.PystBounces
    :inherited-members:

.. autoclass:: pystmark.PystBounce
    :inherited-members:

.. autoclass:: pystmark.PystBounceDump
    :inherited-members:

.. autoclass:: pystmark.PystBounceActivate
    :inherited-members:

.. autoclass:: pystmark.PystBounceTags
    :inherited-members:

.. autoclass:: pystmark.PystDeliveryStats
    :inherited-members:
