.. _advanced_api:

Advanced API
============

.. _advanced_api_sending:

Sending Email
-------------

.. autoclass:: pystmark.Sender
    :inherited-members:

.. autoclass:: pystmark.BatchSender
    :inherited-members:

.. autoclass:: pystmark.TemplateSender
    :inherited-members:

.. autoclass:: pystmark.BatchTemplateSender
    :inherited-members:

.. _advanced_api_bounce_handling:

Bounce Handling
---------------

.. autoclass:: pystmark.Bounces
    :inherited-members:

.. autoclass:: pystmark.Bounce
    :inherited-members:

.. autoclass:: pystmark.BounceDump
    :inherited-members:

.. autoclass:: pystmark.BounceActivate
    :inherited-members:

.. autoclass:: pystmark.BounceTags
    :inherited-members:

.. autoclass:: pystmark.DeliveryStats
    :inherited-members:

.. _advanced_api_bounce_message_details:

Message Details
---------------

.. autoclass:: pystmark.OutboundMessageDetails
    :inherited-members:
