.. module:: pystmark

.. _simple_api:

Simple API
==========

.. _simple_api_sending:

Sending Email
-------------
.. autofunction:: pystmark.send
.. autofunction:: pystmark.send_batch
.. autofunction:: pystmark.send_with_template
.. autofunction:: pystmark.send_batch_with_templates

.. _simple_api_bounce_handling:

Bounce Handling
---------------
.. autofunction:: pystmark.get_bounces
.. autofunction:: pystmark.get_bounce
.. autofunction:: pystmark.get_bounce_dump
.. autofunction:: pystmark.activate_bounce
.. autofunction:: pystmark.get_bounce_tags
.. autofunction:: pystmark.get_delivery_stats

